FROM python:3.14-bookworm AS builder

COPY --from=ghcr.io/astral-sh/uv:0.9.2 /uv /bin/

WORKDIR /app
ENV CONFIG_DIR=/app

COPY requirements.txt .
RUN uv pip install --no-cache --prefix=/install -r requirements.txt

FROM python:3.14-bookworm

RUN apt-get update && apt-get upgrade -y && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN addgroup --system --gid 977 vism && adduser --system --uid 977 --ingroup vism --no-create-home vism

COPY --from=builder /install /usr/local
COPY --chown=vism:vism . .

USER vism

CMD ["python", "main.py", "ca", "start"]
